#!/usr/bin/env bash
# A classic yarn repo that also carries a stray .yarnrc.yml must NOT be treated
# as berry: berry routing runs `yarn npm audit`, a command classic yarn lacks.
set -euo pipefail
BW="$(cd "$(dirname "$0")/.." && pwd)/bin/bumpwright.js"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
cd "$TMP"

# classic lockfile header + the stray berry config file
printf '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n' > yarn.lock
printf 'nodeLinker: node-modules\n' > .yarnrc.yml
printf '{ "name":"c","private":true }' > package.json

node -e '
const src = require("fs").readFileSync(process.argv[1], "utf8");
const fn = src.match(/function isYarnBerry\(\)[\s\S]*?\n}/)[0];
const isYarnBerry = new Function("fs", fn + "; return isYarnBerry;")(require("fs"));
if (isYarnBerry() !== false) { console.error("FAIL: classic lockfile + stray .yarnrc.yml detected as berry"); process.exit(1); }
' "$BW"
echo "CLASSIC STRAY YARNRC OK"

# a real berry lockfile still detects as berry, with or without .yarnrc.yml
printf '# This file is generated by running "yarn install"\n__metadata:\n  version: 8\n' > yarn.lock
rm -f .yarnrc.yml
node -e '
const src = require("fs").readFileSync(process.argv[1], "utf8");
const fn = src.match(/function isYarnBerry\(\)[\s\S]*?\n}/)[0];
const isYarnBerry = new Function("fs", fn + "; return isYarnBerry;")(require("fs"));
if (isYarnBerry() !== true) { console.error("FAIL: berry lockfile not detected as berry"); process.exit(1); }
' "$BW"
echo "BERRY LOCKFILE OK"
